// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.github.diegogomesaraujo.people.grpc;

public interface PersonPhonesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.people.grpc.PersonPhones)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  java.util.List<com.github.diegogomesaraujo.people.grpc.Phone> 
      getPhonesList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  com.github.diegogomesaraujo.people.grpc.Phone getPhones(int index);
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  java.util.List<? extends com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder getPhonesOrBuilder(
      int index);
}
