// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.github.diegogomesaraujo.people.grpc;

/**
 * Protobuf type {@code com.github.diegogomesaraujo.people.grpc.PersonPhones}
 */
public  final class PersonPhones extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.diegogomesaraujo.people.grpc.PersonPhones)
    PersonPhonesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersonPhones.newBuilder() to construct.
  private PersonPhones(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonPhones() {
    phones_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PersonPhones(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              phones_ = new java.util.ArrayList<com.github.diegogomesaraujo.people.grpc.Phone>();
              mutable_bitField0_ |= 0x00000001;
            }
            phones_.add(
                input.readMessage(com.github.diegogomesaraujo.people.grpc.Phone.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        phones_ = java.util.Collections.unmodifiableList(phones_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.diegogomesaraujo.people.grpc.People.internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.diegogomesaraujo.people.grpc.People.internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.diegogomesaraujo.people.grpc.PersonPhones.class, com.github.diegogomesaraujo.people.grpc.PersonPhones.Builder.class);
  }

  public static final int PHONES_FIELD_NUMBER = 1;
  private java.util.List<com.github.diegogomesaraujo.people.grpc.Phone> phones_;
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  public java.util.List<com.github.diegogomesaraujo.people.grpc.Phone> getPhonesList() {
    return phones_;
  }
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  public java.util.List<? extends com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder> 
      getPhonesOrBuilderList() {
    return phones_;
  }
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  public int getPhonesCount() {
    return phones_.size();
  }
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  public com.github.diegogomesaraujo.people.grpc.Phone getPhones(int index) {
    return phones_.get(index);
  }
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
   */
  public com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder getPhonesOrBuilder(
      int index) {
    return phones_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < phones_.size(); i++) {
      output.writeMessage(1, phones_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < phones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, phones_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.diegogomesaraujo.people.grpc.PersonPhones)) {
      return super.equals(obj);
    }
    com.github.diegogomesaraujo.people.grpc.PersonPhones other = (com.github.diegogomesaraujo.people.grpc.PersonPhones) obj;

    boolean result = true;
    result = result && getPhonesList()
        .equals(other.getPhonesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPhonesCount() > 0) {
      hash = (37 * hash) + PHONES_FIELD_NUMBER;
      hash = (53 * hash) + getPhonesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.diegogomesaraujo.people.grpc.PersonPhones parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.diegogomesaraujo.people.grpc.PersonPhones prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.diegogomesaraujo.people.grpc.PersonPhones}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.diegogomesaraujo.people.grpc.PersonPhones)
      com.github.diegogomesaraujo.people.grpc.PersonPhonesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.diegogomesaraujo.people.grpc.People.internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.diegogomesaraujo.people.grpc.People.internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.diegogomesaraujo.people.grpc.PersonPhones.class, com.github.diegogomesaraujo.people.grpc.PersonPhones.Builder.class);
    }

    // Construct using com.github.diegogomesaraujo.people.grpc.PersonPhones.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhonesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.diegogomesaraujo.people.grpc.People.internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_descriptor;
    }

    @java.lang.Override
    public com.github.diegogomesaraujo.people.grpc.PersonPhones getDefaultInstanceForType() {
      return com.github.diegogomesaraujo.people.grpc.PersonPhones.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.diegogomesaraujo.people.grpc.PersonPhones build() {
      com.github.diegogomesaraujo.people.grpc.PersonPhones result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.diegogomesaraujo.people.grpc.PersonPhones buildPartial() {
      com.github.diegogomesaraujo.people.grpc.PersonPhones result = new com.github.diegogomesaraujo.people.grpc.PersonPhones(this);
      int from_bitField0_ = bitField0_;
      if (phonesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.phones_ = phones_;
      } else {
        result.phones_ = phonesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.diegogomesaraujo.people.grpc.PersonPhones) {
        return mergeFrom((com.github.diegogomesaraujo.people.grpc.PersonPhones)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.diegogomesaraujo.people.grpc.PersonPhones other) {
      if (other == com.github.diegogomesaraujo.people.grpc.PersonPhones.getDefaultInstance()) return this;
      if (phonesBuilder_ == null) {
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
      } else {
        if (!other.phones_.isEmpty()) {
          if (phonesBuilder_.isEmpty()) {
            phonesBuilder_.dispose();
            phonesBuilder_ = null;
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000001);
            phonesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhonesFieldBuilder() : null;
          } else {
            phonesBuilder_.addAllMessages(other.phones_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.diegogomesaraujo.people.grpc.PersonPhones parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.diegogomesaraujo.people.grpc.PersonPhones) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.github.diegogomesaraujo.people.grpc.Phone> phones_ =
      java.util.Collections.emptyList();
    private void ensurePhonesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        phones_ = new java.util.ArrayList<com.github.diegogomesaraujo.people.grpc.Phone>(phones_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.diegogomesaraujo.people.grpc.Phone, com.github.diegogomesaraujo.people.grpc.Phone.Builder, com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder> phonesBuilder_;

    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public java.util.List<com.github.diegogomesaraujo.people.grpc.Phone> getPhonesList() {
      if (phonesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phones_);
      } else {
        return phonesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public int getPhonesCount() {
      if (phonesBuilder_ == null) {
        return phones_.size();
      } else {
        return phonesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public com.github.diegogomesaraujo.people.grpc.Phone getPhones(int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);
      } else {
        return phonesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder setPhones(
        int index, com.github.diegogomesaraujo.people.grpc.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder setPhones(
        int index, com.github.diegogomesaraujo.people.grpc.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.set(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder addPhones(com.github.diegogomesaraujo.people.grpc.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder addPhones(
        int index, com.github.diegogomesaraujo.people.grpc.Phone value) {
      if (phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhonesIsMutable();
        phones_.add(index, value);
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder addPhones(
        com.github.diegogomesaraujo.people.grpc.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder addPhones(
        int index, com.github.diegogomesaraujo.people.grpc.Phone.Builder builderForValue) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.add(index, builderForValue.build());
        onChanged();
      } else {
        phonesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder addAllPhones(
        java.lang.Iterable<? extends com.github.diegogomesaraujo.people.grpc.Phone> values) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
      } else {
        phonesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder clearPhones() {
      if (phonesBuilder_ == null) {
        phones_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        phonesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public Builder removePhones(int index) {
      if (phonesBuilder_ == null) {
        ensurePhonesIsMutable();
        phones_.remove(index);
        onChanged();
      } else {
        phonesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public com.github.diegogomesaraujo.people.grpc.Phone.Builder getPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder getPhonesOrBuilder(
        int index) {
      if (phonesBuilder_ == null) {
        return phones_.get(index);  } else {
        return phonesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public java.util.List<? extends com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder> 
         getPhonesOrBuilderList() {
      if (phonesBuilder_ != null) {
        return phonesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phones_);
      }
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public com.github.diegogomesaraujo.people.grpc.Phone.Builder addPhonesBuilder() {
      return getPhonesFieldBuilder().addBuilder(
          com.github.diegogomesaraujo.people.grpc.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public com.github.diegogomesaraujo.people.grpc.Phone.Builder addPhonesBuilder(
        int index) {
      return getPhonesFieldBuilder().addBuilder(
          index, com.github.diegogomesaraujo.people.grpc.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 1;</code>
     */
    public java.util.List<com.github.diegogomesaraujo.people.grpc.Phone.Builder> 
         getPhonesBuilderList() {
      return getPhonesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.diegogomesaraujo.people.grpc.Phone, com.github.diegogomesaraujo.people.grpc.Phone.Builder, com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder> 
        getPhonesFieldBuilder() {
      if (phonesBuilder_ == null) {
        phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.diegogomesaraujo.people.grpc.Phone, com.github.diegogomesaraujo.people.grpc.Phone.Builder, com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder>(
                phones_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        phones_ = null;
      }
      return phonesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.diegogomesaraujo.people.grpc.PersonPhones)
  }

  // @@protoc_insertion_point(class_scope:com.github.diegogomesaraujo.people.grpc.PersonPhones)
  private static final com.github.diegogomesaraujo.people.grpc.PersonPhones DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.diegogomesaraujo.people.grpc.PersonPhones();
  }

  public static com.github.diegogomesaraujo.people.grpc.PersonPhones getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonPhones>
      PARSER = new com.google.protobuf.AbstractParser<PersonPhones>() {
    @java.lang.Override
    public PersonPhones parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PersonPhones(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersonPhones> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonPhones> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.diegogomesaraujo.people.grpc.PersonPhones getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

