// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.github.diegogomesaraujo.people.grpc;

public interface PhoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.people.grpc.Phone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.github.diegogomesaraujo.people.grpc.PhoneType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.github.diegogomesaraujo.people.grpc.PhoneType type = 1;</code>
   */
  com.github.diegogomesaraujo.people.grpc.PhoneType getType();

  /**
   * <code>string number = 2;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
