// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.github.diegogomesaraujo.people.grpc;

public final class People {
  private People() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_people_grpc_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_people_grpc_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_people_grpc_Phone_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_people_grpc_Phone_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_people_grpc_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_people_grpc_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014people.proto\022\'com.github.diegogomesara" +
      "ujo.people.grpc\032\033google/protobuf/empty.p" +
      "roto\"\033\n\010Response\022\017\n\007message\030\001 \001(\t\"Y\n\005Pho" +
      "ne\022@\n\004type\030\001 \001(\01622.com.github.diegogomes" +
      "araujo.people.grpc.PhoneType\022\016\n\006number\030\002" +
      " \001(\t\"~\n\006Person\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t" +
      "\022\013\n\003age\030\003 \001(\005\022\r\n\005email\030\004 \001(\t\022>\n\006phones\030\005" +
      " \003(\0132..com.github.diegogomesaraujo.peopl" +
      "e.grpc.Phone\"N\n\014PersonPhones\022>\n\006phones\030\001" +
      " \003(\0132..com.github.diegogomesaraujo.peopl" +
      "e.grpc.Phone*+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n" +
      "\004HOME\020\001\022\010\n\004WORK\020\0022\336\002\n\rPeopleService\022r\n\nS" +
      "endPerson\022/.com.github.diegogomesaraujo." +
      "people.grpc.Person\0321.com.github.diegogom" +
      "esaraujo.people.grpc.Response\"\000\022Y\n\nListP" +
      "eople\022\026.google.protobuf.Empty\032/.com.gith" +
      "ub.diegogomesaraujo.people.grpc.Person\"\000" +
      "0\001\022~\n\022ListPhonesByPerson\022/.com.github.di" +
      "egogomesaraujo.people.grpc.Person\0325.com." +
      "github.diegogomesaraujo.people.grpc.Pers" +
      "onPhones\"\000B\014B\006PeopleH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_com_github_diegogomesaraujo_people_grpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_diegogomesaraujo_people_grpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_people_grpc_Response_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_github_diegogomesaraujo_people_grpc_Phone_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_diegogomesaraujo_people_grpc_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_people_grpc_Phone_descriptor,
        new java.lang.String[] { "Type", "Number", });
    internal_static_com_github_diegogomesaraujo_people_grpc_Person_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_github_diegogomesaraujo_people_grpc_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_people_grpc_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Email", "Phones", });
    internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_people_grpc_PersonPhones_descriptor,
        new java.lang.String[] { "Phones", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
