// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.github.diegogomesaraujo.people.grpc;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.people.grpc.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();

  /**
   * <code>string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 5;</code>
   */
  java.util.List<com.github.diegogomesaraujo.people.grpc.Phone> 
      getPhonesList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 5;</code>
   */
  com.github.diegogomesaraujo.people.grpc.Phone getPhones(int index);
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 5;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 5;</code>
   */
  java.util.List<? extends com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.people.grpc.Phone phones = 5;</code>
   */
  com.github.diegogomesaraujo.people.grpc.PhoneOrBuilder getPhonesOrBuilder(
      int index);
}
