// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

package com.github.diegogomesaraujo.people.grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.people.grpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
