// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping.proto

package com.github.diegogomesaraujo.store.grpc;

public interface CartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.store.grpc.Cart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.Product products = 1;</code>
   */
  java.util.List<com.github.diegogomesaraujo.store.grpc.Product> 
      getProductsList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.Product products = 1;</code>
   */
  com.github.diegogomesaraujo.store.grpc.Product getProducts(int index);
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.Product products = 1;</code>
   */
  java.util.List<? extends com.github.diegogomesaraujo.store.grpc.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.Product products = 1;</code>
   */
  com.github.diegogomesaraujo.store.grpc.ProductOrBuilder getProductsOrBuilder(
      int index);
}
