// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping.proto

package com.github.diegogomesaraujo.store.grpc;

public interface PaymentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.store.grpc.Payment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.github.diegogomesaraujo.store.grpc.PaymentType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.github.diegogomesaraujo.store.grpc.PaymentType type = 1;</code>
   */
  com.github.diegogomesaraujo.store.grpc.PaymentType getType();

  /**
   * <code>string number = 2;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>string expirationDate = 3;</code>
   */
  java.lang.String getExpirationDate();
  /**
   * <code>string expirationDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getExpirationDateBytes();

  /**
   * <code>string verificationCode = 4;</code>
   */
  java.lang.String getVerificationCode();
  /**
   * <code>string verificationCode = 4;</code>
   */
  com.google.protobuf.ByteString
      getVerificationCodeBytes();
}
