// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping.proto

package com.github.diegogomesaraujo.store.grpc;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.store.grpc.PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.github.diegogomesaraujo.store.grpc.Payment payment = 2;</code>
   */
  boolean hasPayment();
  /**
   * <code>.com.github.diegogomesaraujo.store.grpc.Payment payment = 2;</code>
   */
  com.github.diegogomesaraujo.store.grpc.Payment getPayment();
  /**
   * <code>.com.github.diegogomesaraujo.store.grpc.Payment payment = 2;</code>
   */
  com.github.diegogomesaraujo.store.grpc.PaymentOrBuilder getPaymentOrBuilder();

  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 3;</code>
   */
  java.util.List<com.github.diegogomesaraujo.store.grpc.ProductRPC> 
      getProductsList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 3;</code>
   */
  com.github.diegogomesaraujo.store.grpc.ProductRPC getProducts(int index);
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 3;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 3;</code>
   */
  java.util.List<? extends com.github.diegogomesaraujo.store.grpc.ProductRPCOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 3;</code>
   */
  com.github.diegogomesaraujo.store.grpc.ProductRPCOrBuilder getProductsOrBuilder(
      int index);
}
