// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping.proto

package com.github.diegogomesaraujo.store.grpc;

/**
 * Protobuf enum {@code com.github.diegogomesaraujo.store.grpc.PaymentType}
 */
public enum PaymentType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CREDIT = 0;</code>
   */
  CREDIT(0),
  /**
   * <code>DEBIT = 1;</code>
   */
  DEBIT(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREDIT = 0;</code>
   */
  public static final int CREDIT_VALUE = 0;
  /**
   * <code>DEBIT = 1;</code>
   */
  public static final int DEBIT_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PaymentType valueOf(int value) {
    return forNumber(value);
  }

  public static PaymentType forNumber(int value) {
    switch (value) {
      case 0: return CREDIT;
      case 1: return DEBIT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PaymentType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PaymentType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PaymentType>() {
          public PaymentType findValueByNumber(int number) {
            return PaymentType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.diegogomesaraujo.store.grpc.Store.getDescriptor().getEnumTypes().get(0);
  }

  private static final PaymentType[] VALUES = values();

  public static PaymentType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PaymentType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.github.diegogomesaraujo.store.grpc.PaymentType)
}

