// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping.proto

package com.github.diegogomesaraujo.store.grpc;

public interface ProductResponseRPCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.store.grpc.ProductResponseRPC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 1;</code>
   */
  java.util.List<com.github.diegogomesaraujo.store.grpc.ProductRPC> 
      getProductsList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 1;</code>
   */
  com.github.diegogomesaraujo.store.grpc.ProductRPC getProducts(int index);
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 1;</code>
   */
  java.util.List<? extends com.github.diegogomesaraujo.store.grpc.ProductRPCOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .com.github.diegogomesaraujo.store.grpc.ProductRPC products = 1;</code>
   */
  com.github.diegogomesaraujo.store.grpc.ProductRPCOrBuilder getProductsOrBuilder(
      int index);
}
