// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping.proto

package com.github.diegogomesaraujo.store.grpc;

public interface ProductRequestRPCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.diegogomesaraujo.store.grpc.ProductRequestRPC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   */
  int getPage();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>string id = 3;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 3;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
