// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping.proto

package com.github.diegogomesaraujo.store.grpc;

public final class Store {
  private Store() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductRPC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_store_grpc_ProductRPC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_store_grpc_CartRPC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_store_grpc_CartRPC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductRequestRPC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_store_grpc_ProductRequestRPC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductResponseRPC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_store_grpc_ProductResponseRPC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_diegogomesaraujo_store_grpc_ResponseRPC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_diegogomesaraujo_store_grpc_ResponseRPC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016shopping.proto\022&com.github.diegogomesa" +
      "raujo.store.grpc\032\033google/protobuf/empty." +
      "proto\"J\n\nProductRPC\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030" +
      "\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\r\n\005price\030\004 \001(" +
      "\t\"O\n\007CartRPC\022D\n\010products\030\001 \003(\01322.com.git" +
      "hub.diegogomesaraujo.store.grpc.ProductR" +
      "PC\";\n\021ProductRequestRPC\022\014\n\004page\030\001 \001(\005\022\014\n" +
      "\004size\030\002 \001(\005\022\n\n\002id\030\003 \001(\t\"Z\n\022ProductRespon" +
      "seRPC\022D\n\010products\030\001 \003(\01322.com.github.die" +
      "gogomesaraujo.store.grpc.ProductRPC\",\n\013R" +
      "esponseRPC\022\014\n\004code\030\001 \001(\t\022\017\n\007message\030\002 \001(" +
      "\t2\340\003\n\017ShoppingService\022\207\001\n\014ListProducts\0229" +
      ".com.github.diegogomesaraujo.store.grpc." +
      "ProductRequestRPC\032:.com.github.diegogome" +
      "saraujo.store.grpc.ProductResponseRPC\"\000\022" +
      "t\n\tAddToCart\0222.com.github.diegogomesarau" +
      "jo.store.grpc.ProductRPC\032/.com.github.di" +
      "egogomesaraujo.store.grpc.CartRPC\"\000(\001\022w\n" +
      "\016RemoveFromCart\0222.com.github.diegogomesa" +
      "raujo.store.grpc.ProductRPC\032/.com.github" +
      ".diegogomesaraujo.store.grpc.CartRPC\"\000\022T" +
      "\n\007GetCart\022\026.google.protobuf.Empty\032/.com." +
      "github.diegogomesaraujo.store.grpc.CartR" +
      "PC\"\0002\202\003\n\014StoreService\022z\n\rCreateProduct\0222" +
      ".com.github.diegogomesaraujo.store.grpc." +
      "ProductRPC\0323.com.github.diegogomesaraujo" +
      ".store.grpc.ResponseRPC\"\000\022z\n\rUpdateProdu" +
      "ct\0222.com.github.diegogomesaraujo.store.g" +
      "rpc.ProductRPC\0323.com.github.diegogomesar" +
      "aujo.store.grpc.ResponseRPC\"\000\022z\n\rDeleteP" +
      "roduct\0222.com.github.diegogomesaraujo.sto" +
      "re.grpc.ProductRPC\0323.com.github.diegogom" +
      "esaraujo.store.grpc.ResponseRPC\"\000B\013B\005Sto" +
      "reH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductRPC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_store_grpc_ProductRPC_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Price", });
    internal_static_com_github_diegogomesaraujo_store_grpc_CartRPC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_diegogomesaraujo_store_grpc_CartRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_store_grpc_CartRPC_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductRequestRPC_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductRequestRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_store_grpc_ProductRequestRPC_descriptor,
        new java.lang.String[] { "Page", "Size", "Id", });
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductResponseRPC_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_github_diegogomesaraujo_store_grpc_ProductResponseRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_store_grpc_ProductResponseRPC_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_com_github_diegogomesaraujo_store_grpc_ResponseRPC_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_github_diegogomesaraujo_store_grpc_ResponseRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_diegogomesaraujo_store_grpc_ResponseRPC_descriptor,
        new java.lang.String[] { "Code", "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
